server:
  port: 8380
#数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_qian?useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  #指定应用名称
  application:
    name: consume-service
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8180/eureka/